"""system

Revision ID: 2a832a0dbf4a
Revises: a4a12fee4027
Create Date: 2026-06-26 18:16:10.452305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a832a0dbf4a'
down_revision: Union[str, Sequence[str], None] = 'a4a12fee4027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_states_id'), 'system_states', ['id'], unique=False)
    op.create_index(op.f('ix_system_states_phase_name'), 'system_states', ['phase_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_states_phase_name'), table_name='system_states')
    op.drop_index(op.f('ix_system_states_id'), table_name='system_states')
    op.drop_table('system_states')
    # ### end Alembic commands ###
