"""add_team_promotion_status

Revision ID: 6015e6d4d1a1
Revises: 99ef620daf5b
Create Date: 2026-06-25 15:03:03.070052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6015e6d4d1a1'
down_revision: Union[str, Sequence[str], None] = '99ef620daf5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('is_promoted_to_r2', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'is_promoted_to_r2')
    # ### end Alembic commands ###
