"""add_r2_projects

Revision ID: a4a12fee4027
Revises: 6015e6d4d1a1
Create Date: 2026-06-25 18:46:25.883253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4a12fee4027'
down_revision: Union[str, Sequence[str], None] = '6015e6d4d1a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('repo_url', sa.String(length=255), nullable=False),
    sa.Column('video_demo_url', sa.String(length=255), nullable=True),
    sa.Column('tech_stack', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_index(op.f('ix_project_submissions_id'), 'project_submissions', ['id'], unique=False)
    op.create_table('rubric_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=False),
    sa.Column('ui_ux_score', sa.Float(), nullable=False),
    sa.Column('technical_complexity', sa.Float(), nullable=False),
    sa.Column('innovation', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['judge_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rubric_evaluations_id'), 'rubric_evaluations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rubric_evaluations_id'), table_name='rubric_evaluations')
    op.drop_table('rubric_evaluations')
    op.drop_index(op.f('ix_project_submissions_id'), table_name='project_submissions')
    op.drop_table('project_submissions')
    # ### end Alembic commands ###
